# Generated by Django 4.2 on 2025-10-28 20:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('request', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sla_target', models.DurationField(blank=True, help_text='Duration a project, task, or request should be completed', null=True)),
                ('sla_due', models.DateTimeField(blank=True, help_text='Computed due datetime = created_at + sla_target.', null=True)),
                ('sla_status', models.CharField(choices=[('on_track', 'On Track'), ('due_soon', 'Due Soon'), ('overdue', 'Overdue')], db_index=True, default='on_track', max_length=12)),
                ('sla_breached', models.BooleanField(default=False)),
                ('sla_breached_at', models.DateTimeField(blank=True, help_text='When the SLA was first breached.', null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('wip', 'Work in Progress'), ('completed', 'Completed'), ('deferred', 'Deferred'), ('on-hold', 'On-hold')], default='planned', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_project', to='request.request')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sla_target', models.DurationField(blank=True, help_text='Duration a project, task, or request should be completed', null=True)),
                ('sla_due', models.DateTimeField(blank=True, help_text='Computed due datetime = created_at + sla_target.', null=True)),
                ('sla_status', models.CharField(choices=[('on_track', 'On Track'), ('due_soon', 'Due Soon'), ('overdue', 'Overdue')], db_index=True, default='on_track', max_length=12)),
                ('sla_breached', models.BooleanField(default=False)),
                ('sla_breached_at', models.DateTimeField(blank=True, help_text='When the SLA was first breached.', null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('estimated_hours', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('actual_hours', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Completion percent (0.00 - 100.00)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('scoping', 'Scoping'), ('wip', 'Work in Progress'), ('completed', 'Completed'), ('deferred', 'Deferred'), ('on-hold', 'On-hold')], default='wip', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assigned', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project'], name='projects_ta_project_71fd84_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='projects_ta_status_d6b74c_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to'], name='projects_ta_assigne_e8b2cd_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='projects_ta_due_dat_4757e0_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['sla_status'], name='projects_ta_sla_sta_781f08_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['sla_due'], name='projects_ta_sla_due_7c25e7_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='projects_pr_status_f023cb_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['priority'], name='projects_pr_priorit_a3d3b1_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_manager'], name='projects_pr_project_bf9b53_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['start_date'], name='projects_pr_start_d_9f6d89_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['end_date'], name='projects_pr_end_dat_f8a25b_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['sla_status'], name='projects_pr_sla_sta_98b2d0_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['sla_due'], name='projects_pr_sla_due_a7e268_idx'),
        ),
    ]
