# Generated by Django 4.2 on 2025-10-20 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('account_number', models.CharField(max_length=20)),
                ('currency', models.CharField(default='NGN', max_length=5)),
                ('bank_code', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=150)),
                ('paga_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('is_automated', models.BooleanField(db_index=True, default=True)),
                ('initiator', models.CharField(choices=[('SYSTEM', 'System'), ('USER', 'User'), ('SCHEDULE', 'Scheduled job')], db_index=True, default='SYSTEM', max_length=28)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=128, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_request', models.JSONField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='paga_paymen_status_fdf9a4_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['initiator', 'status'], name='paga_paymen_initiat_9ef82f_idx'),
        ),
    ]
