# Generated by Django 4.2 on 2025-10-28 20:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('request_type', models.CharField(max_length=50)),
                ('system', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('market', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=40)),
                ('estimated_duration_days', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('duration_type', models.CharField(choices=[('short_term', 'Short Term'), ('long_term', 'Long Term')], default='short_term', max_length=10)),
                ('status', models.CharField(choices=[('scoping', 'Scoping'), ('wip', 'Work in Progress'), ('completed', 'Completed'), ('deferred', 'Deferred'), ('on-hold', 'On-hold'), ('converted_to_project', 'Converted to Project')], default='scoping', max_length=30)),
                ('completed_at', models.DateTimeField(blank=True)),
                ('handling_time', models.DurationField(blank=True, null=True)),
                ('sla_status', models.CharField(choices=[('on_track', 'On Track'), ('due_soon', 'Due Soon'), ('overdue', 'Overdue')], default='on_track', max_length=100)),
                ('follow_up', models.BooleanField(default=False)),
                ('requestor_email', models.EmailField(blank=True, max_length=254)),
                ('improvement_type', models.CharField(max_length=60)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_assigned_by', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL)),
                ('requestor_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['status'], name='request_req_status_301325_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['priority'], name='request_req_priorit_6ad0a3_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['assigned_to'], name='request_req_assigne_9964b4_idx'),
        ),
    ]
