# Generated by Django 4.2 on 2025-10-29 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='estimated_duration_days',
        ),
        migrations.RemoveField(
            model_name='request',
            name='handling_time',
        ),
        migrations.AddField(
            model_name='request',
            name='sla_breached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='sla_breached_at',
            field=models.DateTimeField(blank=True, help_text='When the SLA was first breached.', null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='sla_due',
            field=models.DateTimeField(blank=True, help_text='Computed due datetime = created_at + sla_target.', null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='sla_target',
            field=models.DurationField(blank=True, help_text='Duration a project, task, or request should be completed', null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='sla_status',
            field=models.CharField(choices=[('on_track', 'On Track'), ('due_soon', 'Due Soon'), ('overdue', 'Overdue')], db_index=True, default='on_track', max_length=12),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['sla_status'], name='request_req_sla_sta_7e0d6e_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['sla_due'], name='request_req_sla_due_5990c3_idx'),
        ),
    ]
