# Generated by Django 4.2 on 2025-10-29 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_remove_request_estimated_duration_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='requestor_user',
        ),
        migrations.AlterField(
            model_name='request',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
